/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ExecomRouteImport } from './routes/execom'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemberRouteImport } from './routes/member'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ExecomIndexRouteImport } from './routes/execom/index'
import { Route as ExecomActiveProjectsRouteImport } from './routes/execom/active-projects'
import { Route as ExecomHistoryRouteImport } from './routes/execom/history'
import { Route as ExecomMembersRouteImport } from './routes/execom/members'
import { Route as ExecomProjectRequestsRouteImport } from './routes/execom/project-requests'
import { Route as ExecomReportsRouteImport } from './routes/execom/reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecomRoute = ExecomRouteImport.update({
  id: '/execom',
  path: '/execom',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecomIndexRoute = ExecomIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExecomRoute,
} as any)
const ExecomActiveProjectsRoute = ExecomActiveProjectsRouteImport.update({
  id: '/active-projects',
  path: '/active-projects',
  getParentRoute: () => ExecomRoute,
} as any)
const ExecomHistoryRoute = ExecomHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ExecomRoute,
} as any)
const ExecomMembersRoute = ExecomMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ExecomRoute,
} as any)
const ExecomProjectRequestsRoute = ExecomProjectRequestsRouteImport.update({
  id: '/project-requests',
  path: '/project-requests',
  getParentRoute: () => ExecomRoute,
} as any)
const ExecomReportsRoute = ExecomReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ExecomRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRoute
  '/execom': typeof ExecomRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/execom/active-projects': typeof ExecomActiveProjectsRoute
  '/execom/history': typeof ExecomHistoryRoute
  '/execom/members': typeof ExecomMembersRoute
  '/execom/project-requests': typeof ExecomProjectRequestsRoute
  '/execom/reports': typeof ExecomReportsRoute
  '/execom/': typeof ExecomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/execom/active-projects': typeof ExecomActiveProjectsRoute
  '/execom/history': typeof ExecomHistoryRoute
  '/execom/members': typeof ExecomMembersRoute
  '/execom/project-requests': typeof ExecomProjectRequestsRoute
  '/execom/reports': typeof ExecomReportsRoute
  '/execom': typeof ExecomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRoute
  '/execom': typeof ExecomRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/execom/active-projects': typeof ExecomActiveProjectsRoute
  '/execom/history': typeof ExecomHistoryRoute
  '/execom/members': typeof ExecomMembersRoute
  '/execom/project-requests': typeof ExecomProjectRequestsRoute
  '/execom/reports': typeof ExecomReportsRoute
  '/execom/': typeof ExecomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/admin'
    | '/execom'
    | '/forgot-password'
    | '/login'
    | '/member'
    | '/register'
    | '/reset-password'
    | '/execom/active-projects'
    | '/execom/history'
    | '/execom/members'
    | '/execom/project-requests'
    | '/execom/reports'
    | '/execom/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/member'
    | '/register'
    | '/reset-password'
    | '/execom/active-projects'
    | '/execom/history'
    | '/execom/members'
    | '/execom/project-requests'
    | '/execom/reports'
    | '/execom'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/admin'
    | '/execom'
    | '/forgot-password'
    | '/login'
    | '/member'
    | '/register'
    | '/reset-password'
    | '/execom/active-projects'
    | '/execom/history'
    | '/execom/members'
    | '/execom/project-requests'
    | '/execom/reports'
    | '/execom/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AdminRoute: typeof AdminRoute
  ExecomRoute: typeof ExecomRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MemberRoute: typeof MemberRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execom': {
      id: '/execom'
      path: '/execom'
      fullPath: '/execom'
      preLoaderRoute: typeof ExecomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execom/': {
      id: '/execom/'
      path: '/'
      fullPath: '/execom/'
      preLoaderRoute: typeof ExecomIndexRouteImport
      parentRoute: typeof ExecomRoute
    }
    '/execom/active-projects': {
      id: '/execom/active-projects'
      path: '/active-projects'
      fullPath: '/execom/active-projects'
      preLoaderRoute: typeof ExecomActiveProjectsRouteImport
      parentRoute: typeof ExecomRoute
    }
    '/execom/history': {
      id: '/execom/history'
      path: '/history'
      fullPath: '/execom/history'
      preLoaderRoute: typeof ExecomHistoryRouteImport
      parentRoute: typeof ExecomRoute
    }
    '/execom/members': {
      id: '/execom/members'
      path: '/members'
      fullPath: '/execom/members'
      preLoaderRoute: typeof ExecomMembersRouteImport
      parentRoute: typeof ExecomRoute
    }
    '/execom/project-requests': {
      id: '/execom/project-requests'
      path: '/project-requests'
      fullPath: '/execom/project-requests'
      preLoaderRoute: typeof ExecomProjectRequestsRouteImport
      parentRoute: typeof ExecomRoute
    }
    '/execom/reports': {
      id: '/execom/reports'
      path: '/reports'
      fullPath: '/execom/reports'
      preLoaderRoute: typeof ExecomReportsRouteImport
      parentRoute: typeof ExecomRoute
    }
  }
}

interface ExecomRouteChildren {
  ExecomActiveProjectsRoute: typeof ExecomActiveProjectsRoute
  ExecomHistoryRoute: typeof ExecomHistoryRoute
  ExecomMembersRoute: typeof ExecomMembersRoute
  ExecomProjectRequestsRoute: typeof ExecomProjectRequestsRoute
  ExecomReportsRoute: typeof ExecomReportsRoute
  ExecomIndexRoute: typeof ExecomIndexRoute
}

const ExecomRouteChildren: ExecomRouteChildren = {
  ExecomActiveProjectsRoute: ExecomActiveProjectsRoute,
  ExecomHistoryRoute: ExecomHistoryRoute,
  ExecomMembersRoute: ExecomMembersRoute,
  ExecomProjectRequestsRoute: ExecomProjectRequestsRoute,
  ExecomReportsRoute: ExecomReportsRoute,
  ExecomIndexRoute: ExecomIndexRoute,
}

const ExecomRouteWithChildren =
  ExecomRoute._addFileChildren(ExecomRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AdminRoute: AdminRoute,
  ExecomRoute: ExecomRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MemberRoute: MemberRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
